name: qif
description: A Dart Library for Writing QIF Files
version: 0.0.2
homepage: https://github.com/tsteward/qif_dart
author: Timothy Steward <tsteward@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
